### ISSUE TITLE
Welcome screen: Could not load an Orange Workflow file

### ISSUE THREAD

**Issue by JakaKokosar** [biolab/orange3-single-cell#267]
Missing .ows files for:

- Cell type discovery
```
Traceback (most recent call last):
  File "/Users/jakakokosar/OneDrive/dev/orange3-single-cell/dist/scOrange.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 1124, in new_scheme_from
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jakakokosar/OneDrive/dev/orange3-single-cell/dist/scOrange.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/single_cell/tutorials/Showcase-CellType.ows'
```

- Biomarkers
``` 
Traceback (most recent call last):
  File "/Users/jakakokosar/OneDrive/dev/orange3-single-cell/dist/scOrange.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 1124, in new_scheme_from
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jakakokosar/OneDrive/dev/orange3-single-cell/dist/scOrange.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/single_cell/tutorials/Showcase-Markers.ows'
```
- Population prediction
```
Traceback (most recent call last):
  File "/Users/jakakokosar/OneDrive/dev/orange3-single-cell/dist/scOrange.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/application/canvasmain.py", line 1124, in new_scheme_from
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jakakokosar/OneDrive/dev/orange3-single-cell/dist/scOrange.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/single_cell/tutorials/Showcase-Prediction.ows'
```

They were renamed in 5fa56af22a78b6c281d1ba8109cbd0ce9ba0f5a1 but never updated in [config file](https://github.com/biolab/orange3-single-cell/blob/master/orangecontrib/single_cell/launcher/config.py).

**Comment by mstrazar** [comment]
Duplicated issue #241
