### ISSUE TITLE
Louvain Clustering fails (random_state)

### ISSUE THREAD

**Issue by mstrazar** [biolab/orange3-single-cell#321]
Louvain clustering throws an exception

```
Traceback (most recent call last):
  File "/Users/martins/Dev/orange3/Orange/widgets/unsupervised/owlouvainclustering.py", line 282, in __on_done
    result = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/martins/Dev/orange3/Orange/widgets/unsupervised/owlouvainclustering.py", line 595, in run_on_data
    res.partition = louvain.fit_predict(graph)
  File "/Users/martins/Dev/orange3/Orange/clustering/louvain.py", line 149, in fit_predict
    self.fit(X, y)
  File "/Users/martins/Dev/orange3/Orange/clustering/louvain.py", line 142, in fit
    graph, resolution=self.resolution, random_state=self.random_state
TypeError: best_partition() got an unexpected keyword argument 'random_state'
```

##### Single Cell version
aaed13e2201865b24e6e27c26e4da2667aa1e3de
(10. 12. 2018)

##### Orange version
df87c8b58751af7365ea94d4fa76693fa0235c7d
(11. 1. 2019)

##### Additional info (worksheets, data, screenshots, ...)
[workflow-louvain.ows.zip](https://github.com/biolab/orange3-single-cell/files/2749384/workflow-louvain.ows.zip)

**Comment by mstrazar** [comment]
@pavlin-policar can you look at this?

**Comment by pavlin-policar** [comment]
Yes, of course, I didn't notice this.

**Comment by mstrazar** [comment]
Issuenwas due to outdated libraries.
