### ISSUE TITLE
Filter widget crashes when removed from canvas

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-single-cell#322]
##### Steps to reproduce the behavior

Place a Filter widget on canvas and then immediately remove it (do not add any data on its input).

```Traceback (most recent call last):
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 493, in viewStateChanged
    self.updateButtons()
  File "/Users/blaz/.virtualenvs/orange/lib/python3.7/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 1180, in updateButtons
    self.autoBtn.hide()
AttributeError: 'NoneType' object has no attribute 'hide'
```

**Comment by BlazZupan** [comment]
Fixed.
